#############################################################################
# Makefile for building: ganttchart
# Generated by qmake (2.01a) (Qt 4.5.1) on: Sat Mar 20 00:04:04 2010
# Project:  ganttchart.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/lib/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile ganttchart.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt/mkspecs/linux-g++ -I. -I/usr/lib/qt/include/QtCore -I/usr/lib/qt/include/QtGui -I/usr/lib/qt/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib/qt/lib
LIBS          = $(SUBLIBS)  -L/usr/lib/qt/lib -lQtGui -L/usr/lib/qt/lib -L/usr/X11R6/lib -pthread -lpng -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		layoutwidget.cpp \
		task.cpp \
		scheduling.cpp \
		draglabel.cpp \
		ganttchart.cpp moc_layoutwidget.cpp \
		moc_ganttchart.cpp
OBJECTS       = main.o \
		layoutwidget.o \
		task.o \
		scheduling.o \
		draglabel.o \
		ganttchart.o \
		moc_layoutwidget.o \
		moc_ganttchart.o
DIST          = /usr/lib/qt/mkspecs/common/g++.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/debug.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/include_source_dir.prf \
		ganttchart.pro
QMAKE_TARGET  = ganttchart
DESTDIR       = 
TARGET        = ganttchart

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ganttchart.pro  /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/common/g++.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/debug.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt/lib/libQtGui.prl \
		/usr/lib/qt/lib/libQtCore.prl
	$(QMAKE) -spec /usr/lib/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile ganttchart.pro
/usr/lib/qt/mkspecs/common/g++.conf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/debug.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
/usr/lib/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/qt/lib/libQtGui.prl:
/usr/lib/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile ganttchart.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ganttchart1.0.0 || $(MKDIR) .tmp/ganttchart1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ganttchart1.0.0/ && $(COPY_FILE) --parents layoutwidget.h task.h scheduling.h draglabel.h ganttchart.h .tmp/ganttchart1.0.0/ && $(COPY_FILE) --parents main.cpp layoutwidget.cpp task.cpp scheduling.cpp draglabel.cpp ganttchart.cpp .tmp/ganttchart1.0.0/ && (cd `dirname .tmp/ganttchart1.0.0` && $(TAR) ganttchart1.0.0.tar ganttchart1.0.0 && $(COMPRESS) ganttchart1.0.0.tar) && $(MOVE) `dirname .tmp/ganttchart1.0.0`/ganttchart1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ganttchart1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_layoutwidget.cpp moc_ganttchart.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_layoutwidget.cpp moc_ganttchart.cpp
moc_layoutwidget.cpp: ganttchart.h \
		scheduling.h \
		task.h \
		draglabel.h \
		layoutwidget.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) layoutwidget.h -o moc_layoutwidget.cpp

moc_ganttchart.cpp: scheduling.h \
		task.h \
		draglabel.h \
		ganttchart.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) ganttchart.h -o moc_ganttchart.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp layoutwidget.h \
		ganttchart.h \
		scheduling.h \
		task.h \
		draglabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

layoutwidget.o: layoutwidget.cpp layoutwidget.h \
		ganttchart.h \
		scheduling.h \
		task.h \
		draglabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layoutwidget.o layoutwidget.cpp

task.o: task.cpp task.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o task.o task.cpp

scheduling.o: scheduling.cpp scheduling.h \
		task.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scheduling.o scheduling.cpp

draglabel.o: draglabel.cpp draglabel.h \
		task.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o draglabel.o draglabel.cpp

ganttchart.o: ganttchart.cpp ganttchart.h \
		scheduling.h \
		task.h \
		draglabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ganttchart.o ganttchart.cpp

moc_layoutwidget.o: moc_layoutwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layoutwidget.o moc_layoutwidget.cpp

moc_ganttchart.o: moc_ganttchart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ganttchart.o moc_ganttchart.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

